# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

def installed_pods
    pod 'Alamofire', '~> 3.4'
    pod 'RealmSwift'
    pod 'CocoaLumberjack/Swift'
    pod 'ObjectMapper', '~> 1.3'
end

target 'dota2api-swift' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dota2api-swift
    installed_pods


  target 'dota2api-swiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
